plugins {
    id 'com.android.application'
}
android {
    namespace 'com.wifi.extractor'
    compileSdk 34
    defaultConfig {
        applicationId "com.wifi.extractor"
        minSdk 21
        targetSdk 34
        versionCode 1
        versionName "1.0"
    }
    buildTypes {
        release {
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt')
        }
    }
}
dependencies {
    implementation 'androidx.appcompat:appcompat:1.6.1'
}
